name: axiom
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - entrypoints=0.2.3=py36_2
  - grpcio=1.12.1=py36hdbcaa40_0
  - intel-openmp=2018.0.3=0
  - ipython=6.5.0=py36_0
  - jedi=0.12.1=py36_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - mkl=2018.0.3=1
  - nb_conda_kernels=2.1.1=py36_1
  - ncurses=6.1=hf484d3e_0
  - numpy=1.15.0=py36h1b885b7_0
  - numpy-base=1.15.0=py36h3dfced4_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36_0
  - ptyprocess=0.6.0=py36_0
  - python=3.6.6=hc3d631a_0
  - six=1.11.0=py36_1
  - sqlite=3.24.0=h84994c4_0
  - terminado=0.8.1=py36_1
  - traitlets=4.3.2=py36_0
  - xz=5.2.4=h14c3975_4
  - absl-py=0.4.0=py_0
  - arrow-cpp=0.11.1=py36h3bd774a_1
  - astor=0.7.1=py_0
  - backcall=0.1.0=py_0
  - bleach=2.1.4=py_1
  - boost-cpp=1.68.0=h3a22d5f_0
  - bzip2=1.0.6=h470a237_2
  - ca-certificates=2018.8.24=ha4d7672_0
  - certifi=2018.8.24=py36_1
  - dbus=1.13.0=h4e0c4b3_1000
  - decorator=4.3.0=py_0
  - expat=2.2.5=hf484d3e_1002
  - fontconfig=2.13.1=h2176d3f_1000
  - freetype=2.9.1=h94bbf69_1005
  - gast=0.2.0=py_0
  - gettext=0.19.8.1=h9745a5d_1001
  - glib=2.56.2=had28632_1001
  - gmp=6.1.2=hfc679d8_0
  - gst-plugins-base=1.12.5=h3865690_1000
  - gstreamer=1.12.5=h0cc0488_1000
  - html5lib=1.0.1=py_0
  - icu=58.2=hfc679d8_0
  - ipykernel=5.1.0=py36h24bf2e0_1002
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.4.2=py_0
  - jinja2=2.10=py_1
  - jpeg=9c=h14c3975_1001
  - jsonschema=2.6.0=py36_2
  - jupyter=1.0.0=py_1
  - jupyter_client=5.2.3=py_1
  - jupyter_console=5.2.0=py36_1
  - jupyter_core=4.4.0=py_0
  - libiconv=1.15=h14c3975_1004
  - libpng=1.6.36=h84994c4_1000
  - libprotobuf=3.6.0=hd28b015_0
  - libsodium=1.0.16=h470a237_1
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.8=h143f9aa_1005
  - markdown=2.6.11=py_0
  - markupsafe=1.0=py36h470a237_1
  - mistune=0.8.3=py36h470a237_2
  - mkl_fft=1.0.5=py36_0
  - mkl_random=1.0.1=py36_0
  - nb_conda=2.2.1=py36_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py_1
  - notebook=5.6.0=py36_1
  - openssl=1.0.2p=h470a237_0
  - pandas=0.23.4=py36hf8a1672_0
  - pandoc=2.2.2=1
  - pandocfilters=1.4.2=py_1
  - parquet-cpp=1.5.1=2
  - parso=0.3.1=py_0
  - pcre=8.41=hf484d3e_1003
  - pip=18.0=py36_1
  - prometheus_client=0.3.1=py_1
  - prompt_toolkit=1.0.15=py_1
  - protobuf=3.6.0=py36hfc679d8_0
  - pthread-stubs=0.4=h14c3975_1001
  - pyarrow=0.11.1=py36hfc679d8_0
  - pygments=2.2.0=py_1
  - pyqt=5.6.0=py36h13b7fb3_1008
  - python-dateutil=2.7.3=py_0
  - pytz=2018.5=py_0
  - pyzmq=17.1.2=py36hae99301_0
  - qt=5.6.2=hf70d934_9
  - qtconsole=4.4.3=py_0
  - send2trash=1.5.0=py_0
  - setuptools=40.0.0=py36_1
  - simplegeneric=0.8.1=py_1
  - sip=4.18.1=py36hf484d3e_1000
  - sqlalchemy=1.2.11=py36h470a237_0
  - tensorboard=1.10.0=py36_0
  - tensorflow=1.10.0=py36_0
  - termcolor=1.1.0=py_2
  - testpath=0.3.1=py36_1
  - thrift-cpp=0.11.0=he11dc3d_3
  - tornado=5.1=py36h470a237_1
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - werkzeug=0.14.1=py_0
  - wheel=0.31.1=py36_1
  - widgetsnbextension=3.4.2=py36_1000
  - xarray=0.11.3=py36_0
  - xorg-libxau=1.0.8=h14c3975_1006
  - xorg-libxdmcp=1.1.2=h14c3975_1007
  - zeromq=4.2.5=hfc679d8_5
  - libffi=3.2.1=hd88cf55_4
  - readline=7.0=ha6073c6_4
  - tk=8.6.7=hc745277_3
  - zlib=1.2.11=ha838bed_2
  - pip:
    - asn1crypto==0.24.0
    - attrs==18.2.0
    - autobahn==19.1.1
    - automat==0.7.0
    - binance==0.3
    - cachetools==3.1.0
    - cffi==1.11.5
    - chardet==3.0.4
    - constantly==15.1.0
    - cryptography==2.4.2
    - cvxopt==1.2.2
    - cycler==0.10.0
    - dateparser==0.7.0
    - fastavro==0.21.17
    - google-api-core==1.7.0
    - google-auth==1.6.2
    - google-cloud-bigquery==1.9.0
    - google-cloud-core==0.29.1
    - google-resumable-media==0.3.2
    - googleapis-common-protos==1.5.6
    - httplib2==0.12.0
    - hyperlink==18.0.0
    - idna==2.8
    - incremental==17.5.0
    - kiwisolver==1.0.1
    - matplotlib==3.0.2
    - oauth2client==4.1.3
    - pillow==5.3.0
    - pyasn1==0.4.5
    - pyasn1-modules==0.2.3
    - pycparser==2.19
    - pyhamcrest==1.9.0
    - pyopenssl==18.0.0
    - pyparsing==2.3.0
    - python-binance==0.7.0
    - regex==2018.11.22
    - requests==2.21.0
    - rethinkdb==2.3.0.post6
    - rsa==4.0
    - scipy==1.2.0
    - service-identity==18.1.0
    - tflearn==0.3.2
    - twisted==18.9.0
    - txaio==18.8.1
    - tzlocal==1.5.1
    - urllib3==1.24.1
    - zope.interface==4.6.0
prefix: /home/thorad/.conda/envs/axiom

