name: axiom
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - intel-openmp=2018.0.3=0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - mkl=2018.0.3=1
  - ncurses=6.1=hf484d3e_0
  - readline=7.0=ha6073c6_4
  - sqlite=3.24.0=h84994c4_0
  - tk=8.6.7=hc745277_3
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=ha838bed_2
  - absl-py=0.4.0=py_0
  - astor=0.7.1=py_0
  - backcall=0.1.0=py_0
  - bleach=2.1.4=py_1
  - ca-certificates=2018.8.24=ha4d7672_0
  - certifi=2018.8.24=py36_1
  - decorator=4.3.0=py_0
  - entrypoints=0.2.3=py36_2
  - gast=0.2.0=py_0
  - gmp=6.1.2=hfc679d8_0
  - html5lib=1.0.1=py_0
  - ipykernel=4.9.0=py36_0
  - ipython=6.5.0=py36_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.12.1=py36_0
  - jinja2=2.10=py_1
  - jsonschema=2.6.0=py36_2
  - jupyter_client=5.2.3=py_1
  - jupyter_core=4.4.0=py_0
  - libprotobuf=3.6.0=hd28b015_0
  - libsodium=1.0.16=h470a237_1
  - markdown=2.6.11=py_0
  - markupsafe=1.0=py36h470a237_1
  - mistune=0.8.3=py36h470a237_2
  - mkl_fft=1.0.5=py36_0
  - mkl_random=1.0.1=py36_0
  - nb_conda=2.2.1=py36_0
  - nb_conda_kernels=2.1.1=py36_1
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py_1
  - notebook=5.6.0=py36_1
  - openssl=1.0.2p=h470a237_0
  - pandas=0.23.4=py36hf8a1672_0
  - pandoc=2.2.2=1
  - pandocfilters=1.4.2=py_1
  - parso=0.3.1=py_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36_0
  - pip=18.0=py36_1
  - prometheus_client=0.3.1=py_1
  - prompt_toolkit=1.0.15=py_1
  - protobuf=3.6.0=py36hfc679d8_0
  - ptyprocess=0.6.0=py36_0
  - pygments=2.2.0=py_1
  - python-dateutil=2.7.3=py_0
  - pytz=2018.5=py_0
  - pyzmq=17.1.2=py36hae99301_0
  - send2trash=1.5.0=py_0
  - setuptools=40.0.0=py36_1
  - simplegeneric=0.8.1=py_1
  - six=1.11.0=py36_1
  - sqlalchemy=1.2.11=py36h470a237_0
  - tensorboard=1.10.0=py36_0
  - tensorflow=1.10.0=py36_0
  - termcolor=1.1.0=py_2
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36_1
  - tornado=5.1=py36h470a237_1
  - traitlets=4.3.2=py36_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - werkzeug=0.14.1=py_0
  - wheel=0.31.1=py36_1
  - zeromq=4.2.5=hfc679d8_5
  - grpcio=1.12.1=py36hdbcaa40_0
  - numpy=1.15.0=py36h1b885b7_0
  - numpy-base=1.15.0=py36h3dfced4_0
  - python=3.6.6=hc3d631a_0
prefix: /home/thorad/.conda/envs/pgportfolio

